### ISSUE TITLE
[Publisher] Admin Panel: Clean up

### ISSUE THREAD

**Issue by mxosman** [Recidiviz/justice-counts#1075]
- [x] Reasonable responsiveness (#1105)
- [x] Styling adjustments (#1105)
- [x] Figure out how to better sync the loading of the fetched users/agencies (#1103)
- [x] Ensure proper error handling and messaging (#1105)
- [x] Update "System" to "Sector" (#1105)
- [x] Remove superagency system addition/removal -> checkmark update logic b/c it is no longer necessary (user doesn't select the superagency system anymore, the checkmark adds or removes it accordingly) (#1105)
- [x] Fix clash between filter checkmarks and search box in `AgencyProvisioningOverview` (#1105)
